name: trigger-build
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 */8 * * * # each 8 hours

# Dagger plan gets configured via client environment variables
# env:
#   # This needs to be unique across all of netlify.app
#   APP_NAME: todoapp-dagger-europa
#   NETLIFY_TEAM: dagger
jobs:
  publishArmBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Publish ARM build
        uses: dagger/dagger-for-github@v3
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          workdir: pipes
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do publishAll -l=debug --log-format=plain
        env:
          # Get one from https://app.netlify.com/user/applications/personal
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
          GH_USERNAME: ndthanhdev
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: cd
        working-directory: ./scripts
        run: |
          yarn install
          yarn zx ./cd.mjs
        env:
          # Get one from https://app.netlify.com/user/applications/personal
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
          GH_USERNAME: ndthanhdev
